-- CAF Console Multiagente Web v0.5
-- Upgrade seguro sobre o schema do Web MVP.

alter table public.assistencias
  add column if not exists restricoes jsonb not null default '[]'::jsonb,
  add column if not exists faz_deslocamento boolean,
  add column if not exists atende_garantia boolean,
  add column if not exists emite_nota boolean,
  add column if not exists fonte_hash text,
  add column if not exists fonte_importada_em timestamptz not null default now();

alter table public.assistencias
  drop constraint if exists assistencias_restricoes_array;
alter table public.assistencias
  add constraint assistencias_restricoes_array check (jsonb_typeof(restricoes) = 'array');

create or replace function private.has_profile_role(allowed_roles public.profile_role[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and ativo
      and perfil = any(allowed_roles)
  );
$$;
revoke all on function private.has_profile_role(public.profile_role[]) from public, anon;
grant execute on function private.has_profile_role(public.profile_role[]) to authenticated;

create or replace function private.is_reviewer_or_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.has_profile_role(array['revisor', 'administrador']::public.profile_role[]);
$$;
revoke all on function private.is_reviewer_or_admin() from public, anon;
grant execute on function private.is_reviewer_or_admin() to authenticated;

-- O texto importado é uma evidência histórica. Edições posteriores alteram somente campos estruturados.
create or replace function private.preserve_assistance_source_snapshot()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.legacy_id := old.legacy_id;
  new.cabecalho := old.cabecalho;
  new.conteudo_original := old.conteudo_original;
  new.fonte_hash := old.fonte_hash;
  new.fonte_importada_em := old.fonte_importada_em;
  return new;
end;
$$;
revoke all on function private.preserve_assistance_source_snapshot() from public, anon, authenticated;

drop trigger if exists assistencias_preserve_source on public.assistencias;
create trigger assistencias_preserve_source
before update on public.assistencias
for each row execute function private.preserve_assistance_source_snapshot();

-- Conversas determinísticas dos agentes. Nenhum conteúdo depende de IA.
create table if not exists public.agent_conversations (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  agent_id text not null check (agent_id in ('assistencias', 'vendas')),
  titulo text not null default 'Nova conversa',
  state jsonb not null default '{}'::jsonb check (jsonb_typeof(state) = 'object'),
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.agent_conversations(id) on delete cascade,
  role text not null check (role in ('operator', 'assistant', 'system')),
  content text not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists agent_conversations_user_idx
  on public.agent_conversations(user_id, updated_at desc)
  where not archived;
create index if not exists agent_messages_conversation_idx
  on public.agent_messages(conversation_id, created_at, id);

alter table public.agent_conversations enable row level security;
alter table public.agent_messages enable row level security;

create policy agent_conversations_owner_select on public.agent_conversations
for select to authenticated using (user_id = (select auth.uid()));
create policy agent_conversations_owner_insert on public.agent_conversations
for insert to authenticated with check (user_id = (select auth.uid()) and private.is_active_user());
create policy agent_conversations_owner_update on public.agent_conversations
for update to authenticated using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));
create policy agent_conversations_owner_delete on public.agent_conversations
for delete to authenticated using (user_id = (select auth.uid()));

create policy agent_messages_owner_select on public.agent_messages
for select to authenticated using (
  exists (select 1 from public.agent_conversations c where c.id = conversation_id and c.user_id = (select auth.uid()))
);
create policy agent_messages_owner_insert on public.agent_messages
for insert to authenticated with check (
  exists (select 1 from public.agent_conversations c where c.id = conversation_id and c.user_id = (select auth.uid()))
);
create policy agent_messages_owner_delete on public.agent_messages
for delete to authenticated using (
  exists (select 1 from public.agent_conversations c where c.id = conversation_id and c.user_id = (select auth.uid()))
);

create or replace function private.touch_conversation_from_message()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.agent_conversations
  set updated_at = now()
  where id = new.conversation_id;
  return new;
end;
$$;
revoke all on function private.touch_conversation_from_message() from public, anon, authenticated;
drop trigger if exists agent_messages_touch_conversation on public.agent_messages;
create trigger agent_messages_touch_conversation
after insert on public.agent_messages
for each row execute function private.touch_conversation_from_message();

-- Remove políticas amplas do MVP e aplica papéis operacionais.
drop policy if exists assistencias_insert_active on public.assistencias;
drop policy if exists assistencias_update_active on public.assistencias;
drop policy if exists geocode_cache_write_active on public.geocode_cache;
drop policy if exists importacoes_insert_active on public.importacoes;
drop policy if exists importacoes_update_owner_or_admin on public.importacoes;
drop policy if exists importacao_linhas_insert_owner_or_admin on public.importacao_linhas;
drop policy if exists audit_select_active on public.assistencia_audit_log;

create policy assistencias_insert_reviewer on public.assistencias
for insert to authenticated with check (private.is_reviewer_or_admin());
create policy assistencias_update_reviewer on public.assistencias
for update to authenticated using (private.is_reviewer_or_admin())
with check (private.is_reviewer_or_admin());

-- Operadores podem gravar somente o cache de geocodificação, que não contém regras internas.
create policy geocode_cache_write_operator on public.geocode_cache
for all to authenticated using (private.is_active_user()) with check (private.is_active_user());

create policy importacoes_insert_reviewer on public.importacoes
for insert to authenticated with check (
  private.is_reviewer_or_admin() and created_by = (select auth.uid())
);
create policy importacoes_update_reviewer on public.importacoes
for update to authenticated using (
  private.is_reviewer_or_admin() and (created_by = (select auth.uid()) or private.is_admin())
) with check (
  private.is_reviewer_or_admin() and (created_by = (select auth.uid()) or private.is_admin())
);
create policy importacao_linhas_insert_reviewer on public.importacao_linhas
for insert to authenticated with check (
  private.is_reviewer_or_admin() and exists (
    select 1 from public.importacoes i
    where i.id = importacao_id
      and (i.created_by = (select auth.uid()) or private.is_admin())
  )
);
create policy audit_select_reviewer on public.assistencia_audit_log
for select to authenticated using (private.is_reviewer_or_admin());

-- Ranking transparente: status não altera a distância. Grupos são explicitados ao operador.
-- O tipo de retorno desta função mudou em relação à migração inicial.
-- PostgreSQL exige remover a assinatura antiga antes de recriá-la.
drop function if exists public.search_nearby_assistances(
  double precision,
  double precision,
  integer,
  boolean
);

create or replace function public.search_nearby_assistances(
  p_lat double precision,
  p_lng double precision,
  p_limit integer default 8,
  p_include_blocked boolean default false
)
returns table (
  id bigint,
  title text,
  city text,
  uf char(2),
  distance_km double precision,
  score_km double precision,
  status public.assistance_status,
  alert text,
  restrictions jsonb,
  displacement boolean,
  warranty boolean,
  invoice boolean,
  phones jsonb,
  emails jsonb,
  cnpjs jsonb,
  ceps jsonb,
  addresses jsonb,
  latitude double precision,
  longitude double precision,
  geo_source public.geo_source_kind,
  location_label text,
  distance_is_approximate boolean,
  ranking_group text,
  distance_method text,
  distance_label text,
  distance_band text,
  same_distance_group boolean,
  route_allowed boolean,
  blocked_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  with origin as (
    select extensions.st_setsrid(extensions.st_makepoint(p_lng, p_lat), 4326)::extensions.geography as point
  ),
  distances as (
    select
      a.*,
      extensions.st_distance(a.location, o.point) / 1000.0 as raw_distance_km
    from public.assistencias a
    cross join origin o
    where private.is_active_user() and a.ativo
  ),
  blocked as (
    select count(*)::bigint as total
    from distances
    where status = 'NAO_INDICAR'
  ),
  allowed as (
    select
      d.*,
      case when d.status = 'CONSULTAR_ANTES' then 'consult_before' else 'recommended' end as group_name,
      case when d.status = 'CONSULTAR_ANTES' then 1 else 0 end as group_priority,
      case
        when d.geo_source = 'municipality' then concat('municipality:', round(d.raw_distance_km::numeric, 1))
        else concat('precise:', d.id, ':', round(d.raw_distance_km::numeric, 1))
      end as band
    from distances d
    where p_include_blocked or d.status <> 'NAO_INDICAR'
  ),
  selected as (
    select *
    from allowed
    order by group_priority, raw_distance_km, titulo
    limit greatest(1, least(coalesce(p_limit, 8), 20))
  ),
  marked as (
    select s.*, count(*) over (partition by s.band) > 1 as tied
    from selected s
  )
  select
    a.id,
    a.titulo as title,
    a.cidade as city,
    a.uf,
    round(a.raw_distance_km::numeric, 1)::double precision as distance_km,
    a.raw_distance_km as score_km,
    a.status,
    a.alerta as alert,
    a.restricoes as restrictions,
    a.faz_deslocamento as displacement,
    a.atende_garantia as warranty,
    a.emite_nota as invoice,
    a.telefones as phones,
    a.emails,
    a.cnpjs,
    a.ceps,
    a.enderecos as addresses,
    a.effective_latitude as latitude,
    a.effective_longitude as longitude,
    a.geo_source,
    a.geo_label as location_label,
    a.geo_source = 'municipality' as distance_is_approximate,
    a.group_name as ranking_group,
    'haversine'::text as distance_method,
    case
      when a.geo_source = 'municipality' and a.raw_distance_km < 0.1 then 'Mesmo município — ordem interna não determinada'
      when a.geo_source = 'municipality' then 'Distância aproximada entre municípios'
      else 'Distância em linha reta por endereço/coordenada'
    end as distance_label,
    a.band as distance_band,
    a.tied as same_distance_group,
    a.geo_source <> 'municipality' as route_allowed,
    b.total as blocked_count
  from marked a
  cross join blocked b
  order by a.group_priority, a.raw_distance_km, a.titulo;
$$;

revoke all on function public.search_nearby_assistances(double precision, double precision, integer, boolean) from public, anon;
grant execute on function public.search_nearby_assistances(double precision, double precision, integer, boolean) to authenticated;

grant select, insert, update, delete on public.agent_conversations, public.agent_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;
