-- CAF Assistência Web — schema inicial seguro e geográfico.
-- Aplicar em um projeto Supabase novo antes de importar os CSVs de supabase/seed.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create extension if not exists pgcrypto with schema extensions;
create extension if not exists postgis with schema extensions;
create extension if not exists unaccent with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create type public.profile_role as enum ('usuario', 'administrador');
create type public.assistance_status as enum ('NORMAL', 'CONSULTAR_ANTES', 'NAO_INDICAR');
create type public.geo_source_kind as enum ('municipality', 'cep', 'address', 'manual');
create type public.import_status as enum ('ENVIADO', 'VALIDADO', 'PROCESSANDO', 'CONCLUIDO', 'FALHOU', 'CANCELADO');
create type public.import_row_action as enum ('CRIAR', 'ATUALIZAR', 'IGNORAR_DUPLICADO', 'ERRO');
create type public.audit_action as enum ('INSERT', 'UPDATE', 'DELETE', 'ACTIVATE', 'DEACTIVATE');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 1 and 160),
  perfil public.profile_role not null default 'usuario',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.municipios (
  ibge text primary key,
  nome text not null,
  nome_normalizado text not null,
  uf char(2) not null check (uf ~ '^[A-Z]{2}$'),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  location extensions.geography(Point, 4326)
    generated always as (
      extensions.st_setsrid(extensions.st_makepoint(longitude, latitude), 4326)::extensions.geography
    ) stored
);

create table public.assistencias (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  municipio_ibge text not null references public.municipios(ibge),
  cidade text not null,
  cidade_normalizada text not null,
  uf char(2) not null check (uf ~ '^[A-Z]{2}$'),
  titulo text not null check (char_length(trim(titulo)) between 1 and 240),
  cabecalho text not null default '',
  conteudo_original text not null default '',
  status public.assistance_status not null default 'NORMAL',
  alerta text not null default '',
  endereco text not null default '',
  bairro text not null default '',
  cep_principal text not null default '',
  observacoes text not null default '',
  telefones jsonb not null default '[]'::jsonb check (jsonb_typeof(telefones) = 'array'),
  emails jsonb not null default '[]'::jsonb check (jsonb_typeof(emails) = 'array'),
  cnpjs jsonb not null default '[]'::jsonb check (jsonb_typeof(cnpjs) = 'array'),
  ceps jsonb not null default '[]'::jsonb check (jsonb_typeof(ceps) = 'array'),
  enderecos jsonb not null default '[]'::jsonb check (jsonb_typeof(enderecos) = 'array'),
  latitude_municipio double precision not null check (latitude_municipio between -90 and 90),
  longitude_municipio double precision not null check (longitude_municipio between -180 and 180),
  geo_latitude double precision check (geo_latitude between -90 and 90),
  geo_longitude double precision check (geo_longitude between -180 and 180),
  geo_source public.geo_source_kind not null default 'municipality',
  geo_label text not null default '',
  effective_latitude double precision
    generated always as (coalesce(geo_latitude, latitude_municipio)) stored,
  effective_longitude double precision
    generated always as (coalesce(geo_longitude, longitude_municipio)) stored,
  location extensions.geography(Point, 4326)
    generated always as (
      extensions.st_setsrid(
        extensions.st_makepoint(
          coalesce(geo_longitude, longitude_municipio),
          coalesce(geo_latitude, latitude_municipio)
        ),
        4326
      )::extensions.geography
    ) stored,
  ativo boolean not null default true,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((geo_latitude is null and geo_longitude is null) or (geo_latitude is not null and geo_longitude is not null))
);

create table public.geocode_cache (
  cache_key text primary key,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  label text not null,
  source text not null,
  precision text not null,
  updated_at timestamptz not null default now()
);

create table public.importacoes (
  id uuid primary key default extensions.gen_random_uuid(),
  arquivo_nome text not null,
  storage_path text,
  status public.import_status not null default 'ENVIADO',
  total_linhas integer not null default 0 check (total_linhas >= 0),
  novos integer not null default 0 check (novos >= 0),
  atualizados integer not null default 0 check (atualizados >= 0),
  ignorados integer not null default 0 check (ignorados >= 0),
  erros integer not null default 0 check (erros >= 0),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create table public.importacao_linhas (
  id bigint generated by default as identity primary key,
  importacao_id uuid not null references public.importacoes(id) on delete cascade,
  numero_linha integer not null check (numero_linha >= 2),
  dados_originais jsonb not null,
  dados_normalizados jsonb,
  acao_proposta public.import_row_action not null,
  assistencia_id bigint references public.assistencias(id),
  erros jsonb not null default '[]'::jsonb check (jsonb_typeof(erros) = 'array'),
  avisos jsonb not null default '[]'::jsonb check (jsonb_typeof(avisos) = 'array'),
  unique(importacao_id, numero_linha)
);

create table public.assistencia_audit_log (
  id bigint generated by default as identity primary key,
  assistencia_id bigint,
  acao public.audit_action not null,
  dados_anteriores jsonb,
  dados_novos jsonb,
  changed_by uuid references public.profiles(id),
  changed_at timestamptz not null default now()
);

create index municipios_nome_uf_idx on public.municipios(nome_normalizado, uf);
create index municipios_nome_trgm_idx on public.municipios using gin (nome_normalizado extensions.gin_trgm_ops);
create index municipios_location_idx on public.municipios using gist(location);
create index assistencias_location_idx on public.assistencias using gist(location);
create index assistencias_city_uf_idx on public.assistencias(cidade_normalizada, uf) where ativo;
create index assistencias_status_idx on public.assistencias(status) where ativo;
create index assistencias_title_trgm_idx on public.assistencias using gin (titulo extensions.gin_trgm_ops);
create index importacoes_created_by_idx on public.importacoes(created_by, created_at desc);
create index audit_assistance_idx on public.assistencia_audit_log(assistencia_id, changed_at desc);

create or replace function private.normalize_text(input text)
returns text
language sql
stable
set search_path = ''
as $$
  select trim(regexp_replace(upper(extensions.unaccent(coalesce(input, ''))), '[^A-Z0-9]+', ' ', 'g'));
$$;

revoke all on function private.normalize_text(text) from public;
grant execute on function private.normalize_text(text) to authenticated;

create or replace function private.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and ativo
  );
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and ativo and perfil = 'administrador'
  );
$$;

revoke all on function private.is_active_user() from public;
revoke all on function private.is_admin() from public;
grant execute on function private.is_active_user() to authenticated;
grant execute on function private.is_admin() to authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, nome)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), nullif(split_part(new.email, '@', 1), ''), 'Usuário')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;
revoke all on function private.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
revoke all on function private.set_updated_at() from public, anon, authenticated;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger assistencias_set_updated_at
before update on public.assistencias
for each row execute function private.set_updated_at();

create or replace function private.stamp_assistance_user()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by = coalesce(new.created_by, (select auth.uid()));
  else
    new.created_by = old.created_by;
  end if;
  new.updated_by = coalesce((select auth.uid()), new.updated_by);
  return new;
end;
$$;
revoke all on function private.stamp_assistance_user() from public, anon, authenticated;

create trigger assistencias_stamp_user
before insert or update on public.assistencias
for each row execute function private.stamp_assistance_user();

create or replace function private.log_assistance_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  action_value public.audit_action;
begin
  if tg_op = 'INSERT' then
    action_value := 'INSERT';
  elsif tg_op = 'DELETE' then
    action_value := 'DELETE';
  elsif old.ativo and not new.ativo then
    action_value := 'DEACTIVATE';
  elsif not old.ativo and new.ativo then
    action_value := 'ACTIVATE';
  else
    action_value := 'UPDATE';
  end if;

  insert into public.assistencia_audit_log (
    assistencia_id, acao, dados_anteriores, dados_novos, changed_by
  ) values (
    coalesce(new.id, old.id),
    action_value,
    case when tg_op = 'INSERT' then null else to_jsonb(old) - 'location' end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) - 'location' end,
    (select auth.uid())
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;
revoke all on function private.log_assistance_change() from public, anon, authenticated;

create trigger assistencias_audit
after insert or update or delete on public.assistencias
for each row execute function private.log_assistance_change();

alter table public.profiles enable row level security;
alter table public.municipios enable row level security;
alter table public.assistencias enable row level security;
alter table public.geocode_cache enable row level security;
alter table public.importacoes enable row level security;
alter table public.importacao_linhas enable row level security;
alter table public.assistencia_audit_log enable row level security;

create policy profiles_select_self_or_admin on public.profiles
for select to authenticated
using (id = (select auth.uid()) or private.is_admin());

create policy profiles_update_admin on public.profiles
for update to authenticated
using (private.is_admin())
with check (private.is_admin());

create policy municipios_select_active on public.municipios
for select to authenticated
using (private.is_active_user());

create policy assistencias_select_active on public.assistencias
for select to authenticated
using (private.is_active_user());

create policy assistencias_insert_active on public.assistencias
for insert to authenticated
with check (private.is_active_user());

create policy assistencias_update_active on public.assistencias
for update to authenticated
using (private.is_active_user())
with check (private.is_active_user());

create policy assistencias_delete_admin on public.assistencias
for delete to authenticated
using (private.is_admin());

create policy geocode_cache_select_active on public.geocode_cache
for select to authenticated
using (private.is_active_user());

create policy geocode_cache_write_active on public.geocode_cache
for all to authenticated
using (private.is_active_user())
with check (private.is_active_user());

create policy importacoes_select_owner_or_admin on public.importacoes
for select to authenticated
using (created_by = (select auth.uid()) or private.is_admin());

create policy importacoes_insert_active on public.importacoes
for insert to authenticated
with check (private.is_active_user() and created_by = (select auth.uid()));

create policy importacoes_update_owner_or_admin on public.importacoes
for update to authenticated
using (created_by = (select auth.uid()) or private.is_admin())
with check (created_by = (select auth.uid()) or private.is_admin());

create policy importacoes_delete_admin on public.importacoes
for delete to authenticated
using (private.is_admin());

create policy importacao_linhas_select_owner_or_admin on public.importacao_linhas
for select to authenticated
using (
  exists (
    select 1 from public.importacoes i
    where i.id = importacao_id
      and (i.created_by = (select auth.uid()) or private.is_admin())
  )
);

create policy importacao_linhas_insert_owner_or_admin on public.importacao_linhas
for insert to authenticated
with check (
  exists (
    select 1 from public.importacoes i
    where i.id = importacao_id
      and (i.created_by = (select auth.uid()) or private.is_admin())
  )
);

create policy audit_select_active on public.assistencia_audit_log
for select to authenticated
using (private.is_active_user());

create or replace function public.search_municipalities(p_query text, p_limit integer default 8)
returns table (
  ibge text,
  nome text,
  uf char(2),
  latitude double precision,
  longitude double precision,
  relevance real
)
language sql
stable
security invoker
set search_path = ''
as $$
  with normalized as (
    select private.normalize_text(p_query) as value
  )
  select
    m.ibge,
    m.nome,
    m.uf,
    m.latitude,
    m.longitude,
    greatest(
      extensions.similarity(m.nome_normalizado, n.value),
      case when m.nome_normalizado = n.value then 1 else 0 end
    )::real as relevance
  from public.municipios m
  cross join normalized n
  where private.is_active_user()
    and (
      m.nome_normalizado operator(extensions.%) n.value
      or m.nome_normalizado like n.value || '%'
      or n.value like m.nome_normalizado || '%'
    )
  order by relevance desc, m.nome, m.uf
  limit greatest(1, least(coalesce(p_limit, 8), 20));
$$;

create or replace function public.search_nearby_assistances(
  p_lat double precision,
  p_lng double precision,
  p_limit integer default 8,
  p_include_blocked boolean default false
)
returns table (
  id bigint,
  title text,
  city text,
  uf char(2),
  distance_km double precision,
  score_km double precision,
  status public.assistance_status,
  alert text,
  phones jsonb,
  emails jsonb,
  cnpjs jsonb,
  ceps jsonb,
  addresses jsonb,
  latitude double precision,
  longitude double precision,
  geo_source public.geo_source_kind,
  location_label text,
  distance_is_approximate boolean,
  blocked_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  with origin as (
    select extensions.st_setsrid(extensions.st_makepoint(p_lng, p_lat), 4326)::extensions.geography as point
  ),
  distances as (
    select
      a.*,
      extensions.st_distance(a.location, o.point) / 1000.0 as raw_distance_km
    from public.assistencias a
    cross join origin o
    where private.is_active_user() and a.ativo
  ),
  allowed as (
    select *
    from distances
    where p_include_blocked or status <> 'NAO_INDICAR'
  ),
  nearest_allowed as (
    select min(raw_distance_km) as km
    from distances
    where status <> 'NAO_INDICAR'
  ),
  blocked as (
    select count(*)::bigint as total
    from distances d
    cross join nearest_allowed n
    where d.status = 'NAO_INDICAR'
      and d.raw_distance_km <= coalesce(n.km + 100.0, 200.0)
  )
  select
    a.id,
    a.titulo as title,
    a.cidade as city,
    a.uf,
    round(a.raw_distance_km::numeric, 1)::double precision as distance_km,
    a.raw_distance_km as score_km,
    a.status,
    a.alerta as alert,
    a.telefones as phones,
    a.emails,
    a.cnpjs,
    a.ceps,
    a.enderecos as addresses,
    a.effective_latitude as latitude,
    a.effective_longitude as longitude,
    a.geo_source,
    a.geo_label as location_label,
    a.geo_source = 'municipality' as distance_is_approximate,
    b.total as blocked_count
  from allowed a
  cross join blocked b
  order by score_km, distance_km, title
  limit greatest(1, least(coalesce(p_limit, 8), 20));
$$;


create or replace function public.apply_assistance_import(p_importacao_id uuid)
returns table (created_count integer, updated_count integer)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_import public.importacoes%rowtype;
  v_line record;
  v_data jsonb;
  v_municipality jsonb;
  v_address text;
  v_content text;
  v_created integer := 0;
  v_updated integer := 0;
  v_lat double precision;
  v_lng double precision;
begin
  if not private.is_admin() then
    raise exception 'Apenas administradores podem aplicar importações.';
  end if;

  select * into v_import
  from public.importacoes
  where id = p_importacao_id
  for update;

  if not found then
    raise exception 'Importação não encontrada.';
  end if;
  if v_import.status = 'CONCLUIDO' then
    raise exception 'Esta importação já foi aplicada.';
  end if;
  if v_import.erros > 0 then
    raise exception 'A importação possui linhas com erro.';
  end if;

  update public.importacoes set status = 'PROCESSANDO' where id = p_importacao_id;

  for v_line in
    select acao_proposta, assistencia_id, dados_normalizados
    from public.importacao_linhas
    where importacao_id = p_importacao_id
      and acao_proposta in ('CRIAR', 'ATUALIZAR')
    order by numero_linha
  loop
    v_data := v_line.dados_normalizados -> 'data';
    v_municipality := v_line.dados_normalizados -> 'municipality';
    if v_data is null or v_municipality is null then
      raise exception 'Linha validada sem dados normalizados.';
    end if;
    v_lat := nullif(v_data ->> 'latitude', '')::double precision;
    v_lng := nullif(v_data ->> 'longitude', '')::double precision;
    v_address := concat_ws(', ',
      nullif(v_data ->> 'address', ''),
      nullif(v_data ->> 'neighborhood', '')
    );
    v_content := concat_ws(E'\n\n',
      concat(v_data ->> 'city', '/', v_data ->> 'uf'),
      v_data ->> 'title',
      case when jsonb_array_length(coalesce(v_data -> 'cnpjs', '[]'::jsonb)) > 0 then 'CNPJ: ' || array_to_string(array(select jsonb_array_elements_text(v_data -> 'cnpjs')), ' / ') end,
      nullif(v_address, ''),
      case when nullif(v_data ->> 'cep', '') is not null then 'CEP: ' || (v_data ->> 'cep') end,
      case when jsonb_array_length(coalesce(v_data -> 'phones', '[]'::jsonb)) > 0 then array_to_string(array(select jsonb_array_elements_text(v_data -> 'phones')), ' / ') end,
      case when jsonb_array_length(coalesce(v_data -> 'emails', '[]'::jsonb)) > 0 then array_to_string(array(select jsonb_array_elements_text(v_data -> 'emails')), ' / ') end,
      nullif(v_data ->> 'notes', '')
    );

    if v_line.acao_proposta = 'CRIAR' then
      insert into public.assistencias (
        municipio_ibge, cidade, cidade_normalizada, uf, titulo, cabecalho, conteudo_original,
        status, alerta, endereco, bairro, cep_principal, observacoes, telefones, emails, cnpjs, ceps, enderecos,
        latitude_municipio, longitude_municipio, geo_latitude, geo_longitude,
        geo_source, geo_label, ativo
      ) values (
        v_municipality ->> 'ibge', v_data ->> 'city', private.normalize_text(v_data ->> 'city'), v_data ->> 'uf',
        v_data ->> 'title', concat(v_data ->> 'city', '/', v_data ->> 'uf'), v_content,
        coalesce(v_data ->> 'status', 'NORMAL')::public.assistance_status, coalesce(v_data ->> 'alert', ''),
        coalesce(v_data ->> 'address', ''), coalesce(v_data ->> 'neighborhood', ''), coalesce(v_data ->> 'cep', ''), coalesce(v_data ->> 'notes', ''),
        coalesce(v_data -> 'phones', '[]'::jsonb), coalesce(v_data -> 'emails', '[]'::jsonb), coalesce(v_data -> 'cnpjs', '[]'::jsonb),
        case when nullif(v_data ->> 'cep', '') is null then '[]'::jsonb else jsonb_build_array(v_data ->> 'cep') end,
        case when nullif(v_address, '') is null then '[]'::jsonb else jsonb_build_array(v_address) end,
        (v_municipality ->> 'latitude')::double precision, (v_municipality ->> 'longitude')::double precision,
        v_lat, v_lng, (case when v_lat is null then 'municipality' else 'manual' end)::public.geo_source_kind,
        case when v_lat is null then concat(v_municipality ->> 'nome', '/', v_municipality ->> 'uf') else concat_ws(', ', nullif(v_address, ''), concat(v_data ->> 'city', '/', v_data ->> 'uf')) end,
        coalesce((v_data ->> 'active')::boolean, true)
      );
      v_created := v_created + 1;
    else
      update public.assistencias set
        municipio_ibge = v_municipality ->> 'ibge',
        cidade = v_data ->> 'city', cidade_normalizada = private.normalize_text(v_data ->> 'city'), uf = v_data ->> 'uf',
        titulo = v_data ->> 'title', cabecalho = concat(v_data ->> 'city', '/', v_data ->> 'uf'), conteudo_original = v_content,
        status = coalesce(v_data ->> 'status', 'NORMAL')::public.assistance_status, alerta = coalesce(v_data ->> 'alert', ''),
        endereco = coalesce(v_data ->> 'address', ''), bairro = coalesce(v_data ->> 'neighborhood', ''),
        cep_principal = coalesce(v_data ->> 'cep', ''), observacoes = coalesce(v_data ->> 'notes', ''),
        telefones = coalesce(v_data -> 'phones', '[]'::jsonb), emails = coalesce(v_data -> 'emails', '[]'::jsonb), cnpjs = coalesce(v_data -> 'cnpjs', '[]'::jsonb),
        ceps = case when nullif(v_data ->> 'cep', '') is null then '[]'::jsonb else jsonb_build_array(v_data ->> 'cep') end,
        enderecos = case when nullif(v_address, '') is null then '[]'::jsonb else jsonb_build_array(v_address) end,
        latitude_municipio = (v_municipality ->> 'latitude')::double precision,
        longitude_municipio = (v_municipality ->> 'longitude')::double precision,
        geo_latitude = v_lat, geo_longitude = v_lng,
        geo_source = (case when v_lat is null then 'municipality' else 'manual' end)::public.geo_source_kind,
        geo_label = case when v_lat is null then concat(v_municipality ->> 'nome', '/', v_municipality ->> 'uf') else concat_ws(', ', nullif(v_address, ''), concat(v_data ->> 'city', '/', v_data ->> 'uf')) end,
        ativo = coalesce((v_data ->> 'active')::boolean, true)
      where id = v_line.assistencia_id;
      if not found then
        raise exception 'Assistência de atualização não encontrada: %', v_line.assistencia_id;
      end if;
      v_updated := v_updated + 1;
    end if;
  end loop;

  update public.importacoes
  set status = 'CONCLUIDO', finished_at = now()
  where id = p_importacao_id;

  return query select v_created, v_updated;
end;
$$;

revoke all on function public.apply_assistance_import(uuid) from public, anon;
grant execute on function public.apply_assistance_import(uuid) to authenticated;

revoke all on function public.search_municipalities(text, integer) from public, anon;
revoke all on function public.search_nearby_assistances(double precision, double precision, integer, boolean) from public, anon;
grant execute on function public.search_municipalities(text, integer) to authenticated;
grant execute on function public.search_nearby_assistances(double precision, double precision, integer, boolean) to authenticated;

grant usage on schema public to authenticated;
grant select on public.profiles, public.municipios, public.assistencias, public.geocode_cache, public.importacoes, public.importacao_linhas, public.assistencia_audit_log to authenticated;
grant insert, update on public.assistencias, public.geocode_cache, public.importacoes, public.importacao_linhas to authenticated;
grant delete on public.assistencias, public.importacoes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
